// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 03/12/2025, 10:13:15
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Gandoki/Desktop/flux/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Gandoki/Desktop/flux/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Gandoki/Desktop/flux/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Gandoki/Desktop/flux/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Gandoki/Desktop/flux/plugins/**/*.{js,ts,mjs}","C:/Users/Gandoki/Desktop/flux/composables/**/*.{js,ts,mjs}","C:/Users/Gandoki/Desktop/flux/utils/**/*.{js,ts,mjs}","C:/Users/Gandoki/Desktop/flux/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Gandoki/Desktop/flux/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Gandoki/Desktop/flux/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Gandoki/Desktop/flux/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;